### ISSUE TITLE
Deleting  the glfw folder crowds the git changes view

### ISSUE THREAD

**Issue by FuelledByCoffee** [lknknm/ottocento-engine#17]
https://github.com/lknknm/ottocento-engine/blob/b51aa9663afd9ea4ab7090b6aaba20edd4d9af4c/premake5.lua#L38

**Comment by lknknm** [comment]
Weird, I don't see it on my git changes view. 
Would adding it to .gitignore solve the issue?

**Comment by lknknm** [comment]
@FuelledByCoffee provided we changed the build system to Cmake, I can probably mark this issue as solved, right? As dependencies are now fetched through Cmake.
